### ISSUE TITLE
(Urgent) Find alternative to Pastebin for large messages

### ISSUE THREAD

**Issue by misterveiga** [misterveiga/rdss#8]
Pastebin API limit is causing errors in RDSS quick-muting functionality for large messages.
To fix, find an alternative to Pastebin API (for example, a way to post an attachment to Discord and obtain its link) to include in the formatted ;mute String.

**Comment by Gvistic** [comment]
I'm searching for alternatives, however, if you're a pro member you can contact Pastebin and they will increase the limit free of charge.

**Comment by misterveiga** [comment]
Merged fix to master. [Version 1.2.0](https://github.com/misterveiga/rdss/releases/tag/v1.2.0) removes Pastebin implementation in favor of Discord's own attachments.
